name: Google Tests

on:
  push:
    branches:
      - "**"


jobs:

  google-tests:
    name: Run all google tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libboost-all-dev \
            libopenblas-dev \
            liblapack-dev \
            libarpack2-dev \
            libsuperlu-dev \
            libarmadillo-dev \
            libeigen3-dev \
            gfortran \
            libomp-dev \
      - name: Build project
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      - name: Run google Tests
        run: ${{github.workspace}}/build/tests/spinner_test
