name: Google Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  google-tests:
    name: Run all google tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libboost-all-dev \
            libopenblas-dev \
            liblapack-dev \
            libarpack2-dev \
            libsuperlu-dev \
            libarmadillo-dev \
            libeigen3-dev \
            gfortran \
            libomp-dev \
      - name: Build project
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake ..
          cmake --build .
      - name: Run google Tests
        run: ${{github.workspace}}/build/tests/spinner_test

  build-tests:
    name: Build Spinner with different linear algebra packages.
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        linear-algebra: [ libeigen3-dev, libarmadillo-dev ]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libboost-all-dev \
            libopenblas-dev \
            liblapack-dev \
            libarpack2-dev \
            libsuperlu-dev \
            ${{ matrix.linear-algebra }} \
            gfortran \
            libomp-dev \
      - name: Build project
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake ..
          cmake --build .

  build-with-system-gtest:
    name: Build Spinner with system Gtest
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libboost-all-dev \
            libopenblas-dev \
            liblapack-dev \
            libarpack2-dev \
            libsuperlu-dev \
            libeigen3-dev \
            libarmadillo-dev \
            libgtest-dev \
            gfortran \
            libomp-dev \
      - name: Build project
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake ..
          cmake --build .
